# Site language
language: pt-BR

# Site title
title: Victor Otávio

# Short website description
description: Artigos e tutoriais sobre tecnologia e desenvolvimento de software.

# Name to show in the footer
author: Victor Otávio

# Navbar page links
navbar-links:
  Sobre mim: "sobre-mim"

# Image to show in the navigation bar
avatar: "/assets/img/avatar-icon.jpg"
# By default, the image is cut into a circle
round-avatar: true

# Social network links that show in the footer
social-network-links:
  email: "victor@otavioferreira.com.br"
  twitter: vctrtvfrrr
  github: vctrtvfrrr
  gitlab: vctrtvfrrr
  stackoverflow: "2095774/victor-otávio"
  linkedin: victorotavio
  telegram: victorotavio
  spotify: victorotaviof
  reddit: victorotavio
  # youtube: "channel/UCAtVcW5TuVqG_lMGJvyp2ng"
  rss: true

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# Link to website in the footer
url-pretty: "VictorOtavio.com.br"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length
excerpt_length: 50

# Personalize the colors in website
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Enable Disqus comments
disqus: "victorotavio"

# Character used to separate site title and description
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%d/%m/%Y"

# Output options (more information on Jekyll's site)
timezone: "America/Sao_Paulo"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  - scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
